---
title: "Ryan Safner"
format: 
  pdf:
    number_sections: false
#mainfont: Crimson Text
#monofont: Crimson Text
template: cv_template.tex
execute:
  echo: false
  message: false
  warning: false
bibliography:
  - publications.bib
  - underreview.bib
  - workingpapers.bib
  - book-chapters.bib
---

# Appointments

- **U.S. Copyright Office**, Washington, DC
  - 2023- $\quad \quad \quad$ Economist, Office of the Chief Economist
- **Hood College**, Frederick, MD
  - 2022-2023 $\quad$ Associate Professor of Economics (with tenure)
  - 2019-2022 $\quad$ Assistant Professor of Economics 
  - 2016-2019 $\quad$ Visiting Assistant Professor of Economics 
- **Wake Forest University**, Winston-Salem, NC
  - 2015-2016 $\quad$ Visiting Assistant Professor of Economics 
- **George Mason University**, Fairfax, VA
  - 2015 $\quad \quad \; \; \; \; \;$ Adjunct Lecturer
  - 2013-2015 $\quad$ Graduate Lecturer

# Education

- $\quad$ 2015 $\quad \quad$ Ph.D, Economics, *George Mason University*
- $\quad$ 2013 $\quad \quad$ M.A., Economics, *George Mason University*
- $\quad$ 2011 $\quad \quad$ B.A., Economics, *University of Connecticut*

# Research

## Interests

The political economy and economic history of public goods, innovation & technological growth, and intellectual property, using the tools of game theory, new institutional economics, market process economics, and public choice.

## Peer-Reviewed Journal Articles

```{=latex}
\begin{refsection}[publications.bib]     % Set bibliography to publications.bib
\nocite{*}                               % Include all entries
\printbibliography[heading=none]         % Print the bibliography
\end{refsection}
```

## Government Publications

```{=latex}
\begin{refsection}[govt-reports.bib]     % Set bibliography to publications.bib
\nocite{*}                               % Include all entries
\printbibliography[heading=none]         % Print the bibliography
\end{refsection}
```

## Book Chapters

```{=latex}
\begin{refsection}[book-chapters.bib]    % Set bibliography to book-chapters.bib
\nocite{*}                               % Include all entries
\printbibliography[heading=none]         % Print the bibliography
\end{refsection}
```

## Under Review

```{=latex}
\begin{refsection}[underreview.bib]    % Set bibliography to book-chapters.bib
\nocite{*}                               % Include all entries
\printbibliography[heading=none]         % Print the bibliography
\end{refsection}
```

## Working Papers

```{=latex}
\begin{refsection}[workingpapers.bib]    % Set bibliography to book-chapters.bib
\nocite{*}                               % Include all entries
\printbibliography[heading=none]         % Print the bibliography
\end{refsection}
```

# Teaching

## Summary

I have taught a wide variety of economics electives and principles courses. At Hood college, I regularly taught intermediate microeconomics (every semester), econometrics (every fall), and economics electives (1-2 each semester). See links below to my individual course websites, where **all material is made public**. See also [my blog](http://ryansafner.com/post/) for posts relevant to teaching and pedagogy, particularly related to econometrics, data science, and workflow.

## Hood College

- ECMG 212 — Statistics for Economics & Management (S2017)
- ECON 205 — Principles of Macroeconomics (F2018)
- ECON 304 — International Political Economy (F2017) 
- ECON 306 — Microeconomic Analysis (F2016; S2017; F2017; S2018; F2018; S2019; F2019; S2020; F2020; S2021; F2021;  S2022; F2022; [S2023](https://micros23.classes.ryansafner.com))
- ECON 315 — Economics of the Law ([S2021](https://laws21.classes.ryansafner.com)) [**Developed course**]
- ECON 316 — Game Theory (S2019; [F2021](https://gamef21.classes.ryansafner.com))
- ECON 317 — Economics of Development (F0291; [F2021](https://devf21.classes.ryansafner.com))
- ECON 324 — International Trade (F2016; F2018; F2020; [F2022](https://tradef22.classes.ryansafner.com))
- ECON 326 — Industrial Organization (S2017; [S2020](https://ios20.classes.ryansafner.com))
- ECON 410 — Public Economics (S2018; S2020; [S2022](https://publics22.classes.ryansafner.com))
- ECON 452 — History of Economic Thought (F2020; [F2022](https://thoughtf22.classes.ryansafner.com))
- ECON 480 — Econometrics (F2016; F2017; F2018; F2019; F2020; F2021; [F2022](https://metricsf22.classes.ryansafner.com))
- MGMT 399 — Internship for Business (S2018)

## Wake Forest University

- ECN 150 — Introduction to Economics (Fall 2015; Spring 2016)
- ECN 271 — Special Topics: Austrian Economics (Spring 2016)

## George Mason University

- ECON 385 —  International Economic Policy (Summer 2013, Fall 2013, Spring 2014)
- ECON 403 — Austrian Economics (Summer 2015)
- ICES — High School Economics Workshops (Summer 2012, cotaught with Paul Mueller)

# Presentations
- 2024, "Do You Hear the People Sign? Explaining the Increase in Individual Copyright Registrations for Soudn Recordings During the COVID-19 Pandemic," *Society for Economic Research of Copyright Issues* Annual Congress, Fort Worth, TX
- 2024, "The Resilience of Creativity: An Examination of the COVID-19 Impact on Copyright-Reliant Industries and Their Subsequent Recovery," *U.S. Copyright Office* internal presentation
- 2024, "Optimizing Your R Workflow," *Congressional Research Service*
- 2024, "Intellectual Property," guest lecture for *PPEL 420/520 Economic Analysis of the Law, University of Arizona*
- 2023, "Intellectual Property," guest lecture for *PPEL 420/520 Economic Analysis of the Law, University of Arizona*
- 2019, "A Tale of Two Capitals," *Southern Economic Association* Annual Conference, Fort Lauderdale, FL. 
- 2019, "Magic Internet Money? How Blockchain Technology Might Revolutionize the 21st Century Economy," *Phi Kappa Phi* Lecture, Hood College
- 2018, "Distributing Patronage: Intellectual Property in the Transition from Natural State to Open Access Order," *Southern Economic Association* Annual Conference, Washington, DC.
- 2017, "The Network Origins of Economic Growth", *Southern Economic Association* Annual Conference, Tampa, FL.
- 2016, "Ideas, Institutions, and Technological Progress," *Southern Economic Association* Annual Conference, Washington, DC.
- 2015, "Institutional Entrepreneurship, Wikipedia, and the Opportunity of the Commons," *Southern Economic Association* Annual Conference, New Orleans, LA.
- 2015, "Pirate Thy Neighbor: The Protectionist Roots of International Copyright," *Public Choice Society* Annual Conference, San Antonio, TX.
- 2015, "Wiki-nomics: Bringing Institutions Back into Copyright Analysis with a Case Study of Wikipedia," *Public Choice Society* Annual Conference, San Antonio, TX.
- 2014, "Crowdfunding Creative Goods, Crowding out Intellectual Property?" *Southern Economic Association* Annual Conference, Atlanta, GA.
- 2014, "Learning by Doing: Who's Learning? Who's Doing? and other Production Function Myths," (with Santiago Gangotena), *Southern Economic Association* Annual Conference, Atlanta, GA.
- 2014, "'Public Goods' or  'Good for the Public?' - Endogenizing Public Goods," *Association of Private Enterprise Education* Annual Conference, Las Vegas, NV.
- 2014, "A Structural Analysis of Regulatory Capitalism" (with Julia Norgaard and Vlad Tarko), *Association of Private Enterprise Education* Annual Conference, Las Vegas, NV.
- 2014, "Democracy and Political Cost - A Framework for Understanding Political Entrepreneurship in an Entangled Political Economy", *Public Choice Society* Annual Conference, Charleston, SC.
- 2013, "Copyright Since 1976: An Interventionism Framework," *Southern Economic Association* Annual Conference, Tampa, FL.
- 2013, "Towards an Institutional View of Ideas, Copyright, and Piracy," *Institute for Humane Studies*: Symposium on Scholarship and a Free Society, Arlington, VA.

# Professional Development

- 2021, *Institute for Humane Studies* Discussion Colloquium: Scientific Research and Economic Growth
- 2014, *Institute for Humane Studies* and *The Liberty Fund, Inc.* Advanced Topics Seminar: City-States as an Alternative to Nation States. Arlington, VA
- 2013, *Institute for Humane Studies*: Symposium on Scholarship and a Free Society. Arlington, VA
- 2012, *Institute for Humane Studies* and *The Liberty Fund, Inc.* Advanced Topics Seminar: The Growth of Government. Arlington, VA
- 2012, *Institute for Humane Studies* Advanced Studies Seminar: The Challenges and Future of Liberty. Arlington, VA
- 2012, *Institute for Humane Studies* Workshop: Career Development Workshop. Arlington, VA


# Academic Awards and Grants

- Hood College Center for Teaching Academic Innovation Grant 2022
- F.A. Hayek Fund for Scholars (Institute for Humane Studies) 2021
- Hood College Center for Teaching Academic Innovation Grant 2019
- Hood College Board of Associates McCardell Professional Development Grant 2018
- Hood College Board of Associates McCardell Professional Development Grant 2017
- F.A. Hayek Fund for Scholars (Institute for Humane Studies) 2015
- F.A. Hayek Fund for Scholars (Institute for Humane Studies) 2014
- Earhart Foundation Fellowship 2014-2015
- Mercatus Center Graduate Student Summer Research Fellowship 2014
- Graduate Student Travel Fund Grant (George Mason University) 2014
- Earhart Foundation Fellowship 2013-2014
- F. A. Hayek Fund for Scholars (Institute for Humane Studies) 2013
- Dunn Foundation Fellowship 2012-2013

# Consulting

- Member of City of Frederick Mayor's Strategic Opportunities Advisory Team, Economic Resilience Work Group, Ted Gregory, chair (2018)
  - 2018 *Report of the Strategic Opportunities Advisory Team*

# Service

## To Hood College

- Panel discussant for "The Crisis in Ukraine" Panel, Hood College, March 11, 2022
- Member of Curriculum Committee (Fall 2018—Spring 2020)
    - Committee Chair (Fall 2019—Spring 2020)
- Member of SPIRES Committee (Fall 2019—Spring 2021)
    - Inaugural SPIRES symposium (April 2021)
- Member of TEDx Committee (Fall 2021)
- Chaired search committee for Visiting Assistant Professor of Economics (2019-2020) position (successful hire)
- Taught mini-course "Magic Internet Money? How Blockchain Technology Could Revolutionize the 21st Century Economy," Accepted Students Day, April 6, 2019
- Panel discussant for "The EU: Dead At 60?" Panel, Hood College, September 7, 2018
- Created and approved new economics course: ECON 315 — Economics of the Law (2020)
- Proposed change to Economics major, approved by the Curriculum Committee (Spring 2018)
- Taught mini-course "A Pirate's Life for Me — The Economics of Intellectual Property and (Digital) Piracy", Accepted Students Day, April 11, 2018
- Taught mini-course "A Pirate's Life for Me — The Economics of Intellectual Property and (Digital) Piracy", Accepted Students Day, April 8, 2017
- Panel discussant for "Globalization and Its Discontents" Panel, Hood College, March 2, 2017
- Committee chair for Departmental Honors Thesis undergraduate students:
  - Maria Silva (2021-2022)
  - Anubhooti Regmi (2021-2022)
  - Natalie Kolosieke (2020—2021)
  - Kevin Ciocco (2020—2021)
  - Valentin Donchev (2019—2020)
  - Emily Stubits (2019—2020)
  - Elias Nicholson (2018—2019)
    - Nicholson, Elias, 2019, "Regulation and Discrimination: Race and Interest Rate Mark-Ups in the Auto Loan Industry," [*Issues in Political Economy*](https://blogs.elon.edu/ipe/issues/volume-28-issue-1/) 28(1)
  - Zack Miller (2016—2017)
- Committee member for Departmental Honors Thesis undergraduate students:
  - Jakob Stubits (2022-2023)
  - Jared Knowles (2016-2017)
  - Jaclyn Bealer (2016-2017)
- Department Library Liason (Fall 2016--Fall 2020)

## To Wake Forest University

- Committee member for Senior Thesis undergraduate student Adrian Martino (WFU, 2016);

## To the Profession

- Reviewer for *Journal of Institutional Economics*, *European Journal of Law and Economics*, and *Review of Austrian Economics*
- Scientific Committee Member for *Panchonomist*
- Faculty reviewer for *Institute for Humane Studies*' Humane Studies Fellowships (2016, 2017)

## Professional Memberships

- American Law & Economics Association
- Society for the Development of Austrian Economics
- Southern Economic Association
- American Economic Association
- Phi Kappa Phi Honor Society

# Skills

- Languages:
  - English (native), Russian (conversational), Spanish (conversational)
- Programming:
  - R, Stata, Python, NetLogo, Quarto, LaTeX, SQL, Git
