---
title: "CV"
author: Ryan Safner

jobtitle: "Assistant Professor of Economics"
department: "George B. Delaplaine Jr. School of Business"
address: "**Hood College**, Frederick, MD 21701"
email: safner@hood.edu
github: ryansafner
web: ryansafner.com

keywords: Ryan Safner, economics, CV, Hood College
date: "`r Sys.Date()`"
output: 
  pdf_document:
    number_sections: false
    template: template.tex
    #pandoc_args: "--pdf-engine-opt=--enable-write18"
    latex_engine: xelatex

mainfont: Fira Sans Condensed
sansfont: Fira Sans Condensed
---

# Academic Appointments {-}

- **Hood College** -- Frederick, MD
    - Assistant Professor of Economics (2019--Present)
  	- Visiting Assistant Professor of Economics (2016--2019)	
- **Wake Forest University** -- Winston-Salem, NC
    - Visiting Assistant Professor of Economics (2015--2016)
- **George Mason University** -- Fairfax, VA
  - Adjunct Lecturer (Summer 2015)
  - Graduate Lecturer (Summer 2013, Fall 2013, Spring 2014)

# Education {-}

- Ph.D. (Economics), George Mason University, 2015
    - Dissertation: *Essays on the Institutional Analysis of Copyright and its Alternatives*
- M.A. (Economics), George Mason University, 2013
- B.A. (Economics), University of Connecticut, 2011

# Research {-}

## Peer-Reviewed Journal Articles {-}

- Safner, Ryan, 2016, "[Institutional Entrepreneurship, Wikipedia, and the Opportunity of the Commons](http://papers.ssrn.com/sol3/papers.cfm?abstract_id=2564230)," *Journal of Institutional Economics* 12(4): 743-771 
- Safner, Ryan, 2016, "[The Perils of Copyright Regulation](http://papers.ssrn.com/sol3/papers.cfm?abstract_id=2396874)," *The Review of Austrian Economics* 29(2): 121-137

## Under Review {-}

- [The Production of Increasing Returns: Physical Technology, Institutional Technoloy, and the Pitfalls of Production Functions](http://papers.ssrn.com/sol3/papers.cfm?abstract_id=2626587) (with Santiago Gangotena)
- "['Public Goods' or 'Good for the Public?' How Political Entrepreneurship Endogenizes Public Goods](http://ssrn.com/abstract=2488655)"

## Working Papers {-}

- "A Tale of Two Capitals: Modelling the Interaction between Ideas, Physical Capital, and Growth" (with Santiago Gangotena)
- "[Distributing Patronage: Intellectual Property in the Transition from Natural State to Open Access Order](http://papers.ssrn.com/abstract=2499621)"
- "[Pirate Thy Neighbor: The Protectionist Roots of International Copyright](http://papers.ssrn.com/sol3/papers.cfm?abstract_id=2564232)"
- "Kickstart My Art: Is Crowdfunding a Substitute or a Complement to Intellectual Property Laws?" 
- "A Structural Analysis of Regulatory Capitalism" (with Julia Norgaard and Vlad Tarko)
- "Ideas, Networks, and Institutions" (with Santiago Gangotena, Pedro Romero, and Alex Xerves) 
- "Patent Warlords: How the Logic of the Natural State Holds Innovation Hostage"
- "Crypto-Copyright: The Potential of Protecting Intellectual Property with the Blockchain"

## Research Interests {-}

Public goods, innovation & technological growth, and intellectual property, using the tools of game theory, new institutional economics, market process economics, and public choice

# Teaching {-}

## Hood College {-}

- ECMG 212 -- Statistics for Economics & Management (Spring 2017)
- ECON 205 -- Principles of Macroeconomics (Fall 2018)
- ECON 304 -- International Political Economy (Fall 2017) 
- ECON 306 -- Microeconomic Analysis (Fall 2016; Spring 2017; Fall 2017; Spring 2018; Fall 2018; Spring 2019; Fall 2019; [Spring 2020](https://micros20.classes.ryansafner.com); Fall 2020)
- ECON 316 -- Game Theory (Spring 2019)
- ECON 317 -- Economics of Development ([Fall 2019](https://devf19.classes.ryansafner.com))
- ECON 324 -- International Trade (Fall 2016; Fall 2018; [Fall 2020](https://tradef20.classes.ryansafner.com))
- ECON 326 -- Industrial Organization (Spring 2017; [Spring 2020](https://ios20.classes.ryansafner.com))
- ECON 410 -- Public Economics (Spring 2018; [Spring 2020](https://publics20.classes.ryansafner.com))
- ECON 452 -- History of Economic Thought ([Fall 2020](https://thoughtf20.classes.ryansafner.com))
- ECON 480 -- Econometrics (Fall 2016; Fall 2017; Fall 2018; Fall 2019; [Fall 2020](https://metricsf20.classes.ryansafner.com))
- MGMT 399 -- Internship for Business (Spring 2018)

- See also [my blog](http://ryansafner.com/post/) for posts relevant to teaching and pedagogy, particularly related to econometrics, data science, and workflow

## Wake Forest University {-}

- ECN 150 -- Introduction to Economics (Fall 2015; Spring 2016)	
- ECN 271 -- Special Topics: Austrian Economics (Spring 2016) 

## George Mason University {-}

- ECON 385 --  International Economic Policy (Summer 2013, Fall 2013, Spring 2014)
- ECON 403 -- Austrian Economics (Summer 2015)
- ICES -- High School Economics Workshops (Summer 2012, cotaught with Paul Mueller)

## Academic Presentations {-}

- 2019, "A Tale of Two Capitals," *Southern Economic Association* Annual Conference, Fort Lauderdale, FL. 
- 2019, "Magic Internet Money? How Blockchain Technology Might Revolutionize the 21st Century Economy," *Phi Kappa Phi* Lecture, Hood College
- 2018, "Distributing Patronage: Intellectual Property in the Transition from Natural State to Open Access Order," *Southern Economic Association* Annual Conference, Washington, DC.
- 2017, "The Network Origins of Economic Growth", *Southern Economic Association* Annual Conference, Tampa, FL.
- 2016, "Ideas, Institutions, and Technological Progress," *Southern Economic Association* Annual Conference, Washington, DC.
- 2015, "Institutional Entrepreneurship, Wikipedia, and the Opportunity of the Commons," *Southern Economic Association* Annual Conference, New Orleans, LA.
- 2015, "Pirate Thy Neighbor: The Protectionist Roots of International Copyright," *Public Choice Society* Annual Conference, San Antonio, TX.
- 2015, "Wiki-nomics: Bringing Institutions Back into Copyright Analysis with a Case Study of Wikipedia," *Public Choice Society* Annual Conference, San Antonio, TX.
- 2014, "Crowdfunding Creative Goods, Crowding out Intellectual Property?" *Southern Economic Association* Annual Conference, Atlanta, GA.
- 2014, "Learning by Doing: Who's Learning? Who's Doing? and other Production Function Myths," (with Santiago Gangotena), *Southern Economic Association* Annual Conference, Atlanta, GA.
- 2014, "'Public Goods' or  'Good for the Public?' - Endogenizing Public Goods," *Association of Private Enterprise Education* Annual Conference, Las Vegas, NV.
- 2014, "A Structural Analysis of Regulatory Capitalism" (with Julia Norgaard and Vlad Tarko), *Association of Private Enterprise Education* Annual Conference, Las Vegas, NV.
- 2014, "Democracy and Political Cost - A Framework for Understanding Political Entrepreneurship in an Entangled Political Economy", *Public Choice Society* Annual Conference, Charleston, SC.
- 2013, "Copyright Since 1976: An Interventionism Framework," *Southern Economic Association* Annual Conference, Tampa, FL.
- 2013, "Towards an Institutional View of Ideas, Copyright, and Piracy," *Institute for Humane Studies*: Symposium on Scholarship and a Free Society, Arlington, VA.

# Professional Development {-}

- 2014, *Institute for Humane Studies* and *The Liberty Fund, Inc.* Advanced Topics Seminar: City-States as an Alternative to Nation States. Arlington, VA
- 2013, *Institute for Humane Studies*: Symposium on Scholarship and a Free Society. Arlington, VA
- 2012, *Institute for Humane Studies* and *The Liberty Fund, Inc.* Advanced Topics Seminar: The Growth of Government. Arlington, VA
- 2012, *Institute for Humane Studies* Advanced Studies Seminar: The Challenges and Future of Liberty. Arlington, VA
- 2012, *Institute for Humane Studies* Workshop: Career Development Workshop. Arlington, VA

# Academic Awards and Grants {-}

- Hood College Center for Teaching Academic Innovation Grant 2019
- Hood College Board of Associates McCardell Professional Development Grant 2018
- Hood College Board of Associates McCardell Professional Development Grant 2017
- F. A. Hayek Fund for Scholars (Institute for Humane Studies) 2015
- F. A. Hayek Fund for Scholars (Institute for Humane Studies) 2014
- Earhart Foundation Fellowship 2014-2015
- Mercatus Center Graduate Student Summer Research Fellowship 2014
- Graduate Student Travel Fund Grant (George Mason University) 2014
- Earhart Foundation Fellowship 2013-2014
- F. A. Hayek Fund for Scholars (Institute for Humane Studies) 2013
- Dunn Foundation Fellowship 2012-2013

# Professional Memberships {-}

- Society for the Development of Austrian Economics
- Southern Economic Association
- American Economic Association
- Phi Kappa Phi Honor Society

# Consulting {-}

- Member of City of Frederick Mayor's Strategic Opportunities Advisory Team, Economic Resilience Work Group, Ted Gregory, chair (2018) 	

# Service {-}

## To Hood College {-}

- Member of Curriculum Committee (Fall 2018--Spring 2020)
    - Committee Chair (Fall 2019--Spring 2020)
- Member of SPIRES Committee (Fall 2019--Spring 2020)
- Chaired search committee for Visiting Assistant Professor of Economics (2019-2020) position (successful hire)
- Taught mini-course "Magic Internet Money? How Blockchain Technology Could Revolutionize the 21st Century Economy," Accepted Students Day, April 6, 2019
- Panel discussant for "The EU: Dead At 60?" Panel, Hood College, September 7, 2018
- Proposed change to Economics major, approved by the Curriculum Committee (Spring 2018)
- Taught mini-course "A Pirate's Life for Me -- The Economics of Intellectual Property and (Digital) Piracy", Accepted Students Day, April 11, 2018
- Taught mini-course "A Pirate's Life for Me -- The Economics of Intellectual Property and (Digital) Piracy", Accepted Students Day, April 8, 2017
- Panel discussant for "Globalization and Its Discontents" Panel, Hood College, March 2, 2017
- Committee chair for Departmental Honors Thesis undergraduate students Elias Nicholson (2018-2019); Zack Miller (2016-2017)
    - Elias Nicholson's thesis published as Nicholson, Elias, 2019, "Regulation and Discrimination: Race and Interest Rate Mark-Ups in the Auto Loan Industry," [*Issues in Political Economy*](https://blogs.elon.edu/ipe/issues/volume-28-issue-1/) 28(1) 
- Committee member for Departmental Honors Thesis undergraduate students Jaclyn Bealer (2016-2017); Jared Knowles (2016-2017)
- Department Library Liason (Fall 2016--Present)

## To the Profession {-}

- Reviewer for *Journal of Institutional Economics*, *European Journal of Law and Economics*, and *Review of Austrian Economics* 
- Committee member for Senior Thesis undergraduate student Adrian Martino (WFU, 2016);
- Faculty reviewer for *Institute for Humane Studies*' Humane Studies Fellowships (2016, 2017) 